<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
        <EmbeddedResource Include="Shaders\**\*.sksl"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.1.2"/>
        <PackageReference Include="Avalonia.Desktop" Version="12.1.2"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.2"/>
        <PackageReference Include="Avalonia.Markup.Xaml.Loader" Version="12.1.2" PrivateAssets="All" Publish="True"/>
        <PackageReference Include="HotAvalonia" Version="3.*" PrivateAssets="All" Publish="True"/>
        <PackageReference Include="MonoMod.RuntimeDetour" Version="*" PrivateAssets="All"/>
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="SukiUI" Version="7.0.2-nightly20260918.461" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\GoodByeDPI.Core\GoodByeDPI.Core.csproj"/>
    </ItemGroup>
</Project>
