<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
        <EmbeddedResource Include="Shaders\**\*.sksl"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.1.2"/>
        <PackageReference Include="Avalonia.Desktop" Version="12.1.2"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.2"/>
        <PackageReference Include="Avalonia.Markup.Xaml.Loader" Version="12.1.2" PrivateAssets="All" Publish="True"/>
        <PackageReference Include="HotAvalonia" Version="3.*" PrivateAssets="All" Publish="True"/>
        <PackageReference Include="MonoMod.RuntimeDetour" Version="*" PrivateAssets="All"/>
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="SukiUI" Version="7.0.2-nightly20260918.461" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\GoodByeDPI.Core\GoodByeDPI.Core.csproj"/>
    </ItemGroup>

    <Target Name="GenerateDynamicManifest" BeforeTargets="BeforeBuild" Condition="'$(Configuration)' == 'Release'">
        <PropertyGroup>
            <GeneratedManifestPath>$(IntermediateOutputPath)dynamic.app.manifest</GeneratedManifestPath>
        </PropertyGroup>

        <ModifyManifest InputPath="app.manifest" OutputPath="$(GeneratedManifestPath)"/>

        <PropertyGroup>
            <ApplicationManifest>$(GeneratedManifestPath)</ApplicationManifest>
        </PropertyGroup>
    </Target>

    <UsingTask TaskName="ModifyManifest" TaskFactory="RoslynCodeTaskFactory" AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll">
        <ParameterGroup>
            <InputPath ParameterType="System.String" Required="true"/>
            <OutputPath ParameterType="System.String" Required="true"/>
        </ParameterGroup>
        <Task>
            <Using Namespace="System.IO"/>
            <Using Namespace="System.Xml"/>
            <Code Type="Fragment" Language="cs">
                <![CDATA[
                    XmlDocument doc = new XmlDocument();
                    doc.Load(InputPath);

                    XmlNamespaceManager nsmgr = new XmlNamespaceManager(doc.NameTable);
                    nsmgr.AddNamespace("asmv3", "urn:schemas-microsoft-com:asm.v3");

                    XmlNode node = doc.SelectSingleNode("//asmv3:requestedExecutionLevel", nsmgr);
                    if (node != null)
                    {
                        node.Attributes["level"].Value = "requireAdministrator";
                    }

                    string dir = Path.GetDirectoryName(OutputPath);
                    if (!string.IsNullOrEmpty(dir))
                    {
                        Directory.CreateDirectory(dir);
                    }
                    doc.Save(OutputPath);
                ]]>
            </Code>
        </Task>
    </UsingTask>
</Project>
